name: 'Veinmind'
description: 'Scan images for security issues with veinmind'
author: 'Veinmind Team'
branding:
  color: purple
  icon: check-circle
inputs:
  image-ref:
    description: 'used to select scan Image name'
    required: true
  register-token:
    description: 'used to identify the organization'
    required: true
  timeout:
    description: 'used to limit pipeline timeout (default 10 min)'
    required: false
    default: '10'
  focus:
    description: 'focus mode(only output key vul (default: 0/off)'
    required: false
    default: '0'
runs:
  using: 'composite'
  steps:
    - run: docker run --rm --mount 'type=bind,source=/,target=/host,readonly,bind-propagation=rslave' -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/tool/resource veinmind/veinmind-agent:v2.1.5 ci -a -s https://veinmind-cood.rivers.chaitin.cn/server/list -c https://veinmind-cood.rivers.chaitin.cn/server/ca -t ${{ inputs.register-token }} --image ${{ inputs.image-ref }} --timeout ${{ inputs.timeout }} --focus ${{ inputs.focus }} -p 1
      shell: bash
    # - run: wget --progress=dot:giga https://veinmind-cood.rivers.chaitin.cn/unauth/agent_download -O ./agent.tar.gz && docker load --input agent.tar.gz && docker run --rm --mount 'type=bind,source=/,target=/host,readonly,bind-propagation=rslave' -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/tool/resource $(docker images --format "{{.Repository}}:{{.Tag}}" | grep 'veinmind/veinmind-agent') ci -c https://veinmind-cood.rivers.chaitin.cn/server/ca -s https://veinmind-cood.rivers.chaitin.cn/server/list -t ${{ inputs.register-token }} --image ${{ inputs.image-ref }} --timeout ${{ inputs.timeout }} --focus ${{ inputs.focus }}
    #   shell: bash
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ inputs.output }}
    #     path: ${{ inputs.output }}
        