on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test veinmind action
    steps:
      - uses: actions/checkout@v3
      # - uses: dvkunion/CollieTrickster@main
      #   with:
      #     token: ${{ secrets.COLLIETOKEN }}
      - uses: asjdf/veinmind-action@main
        with:
          register-token: ${{ secrets.REGISTERTOKEN }}
          image-ref: ubuntu:20.04